workspace = { members = [ 
    "Prototypes/manga109api",
    "Prototypes/tesseract_textboxed", 
    "training/text_detection/tools/convert_annotations_to_yolo"] }
[package]
name = "ml_manga_ocr"
version = "0.1.0"
edition = "2021"
